// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoftagajdlcmusdbnblm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZnRhZ2FqZGxjbXVzZGJuYmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjIyNjMsImV4cCI6MjA1NTYzODI2M30.Xa3Isc3xy5Vv8pWC_sefY-lOuz5v-4Q99HSKPnCjraE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);